# Generated by Django 2.2.6 on 2019-10-06 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_nam', models.CharField(max_length=200, verbose_name='название статьи')),
                ('stat_text', models.TextField(verbose_name='текст статьи')),
                ('pub_date', models.DateTimeField(verbose_name='дата')),
            ],
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment_auther', models.CharField(max_length=50, verbose_name='имя автора')),
                ('coment_text', models.CharField(max_length=200, verbose_name='текст автора')),
                ('kay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Stat')),
            ],
        ),
    ]
