# Generated by Django 2.2.6 on 2019-10-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191006_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meadia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
