# Generated by Django 2.2.6 on 2019-10-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_meadia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meadia',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
