# Generated by Django 2.2.6 on 2019-10-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191006_0910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meadia',
        ),
        migrations.AddField(
            model_name='stat',
            name='img_stat',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
