# Generated by Django 2.2.6 on 2019-10-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191009_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='img_stat',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
