# Generated by Django 2.2.6 on 2019-10-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logo',
            new_name='Img_logo',
        ),
    ]
