# Generated by Django 2.2.6 on 2019-10-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191012_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img_logo',
        ),
    ]
